version: "3.9"

services:
  app:
    build: .
    ports:
      - "8080:8888"
  worker:
    build: .
    command: ["python", "huey_consumer.py", "main.huey"]
  redis:
    image: "redis:alpine"
    command: redis-server
    ports:
      - "6379:6379"
    expose:
      - "6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis-data:/data
      - redis-conf:/usr/local/etc/redis/redis.conf
volumes:
  redis-data:
  redis-conf:
