DB_USER='zqoxqsij'
DB_PASS='sa8Mrsk9cgK35RlEDKwDrUccVLbRr3nv'
DB_URL='postgres://zqoxqsij:sa8Mrsk9cgK35RlEDKwDrUccVLbRr3nv@drona.db.elephantsql.com/zqoxqsij'
DB_NAME = 'zqoxqsij'
DB_HOST = 'drona.db.elephantsql.com'